apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-app-2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: example-app-2
    repoURL: https://github.com/maxpschonder/argocd-examples.git
    targetRevision: {{ .Values.targetRevision }}
    helm:
      valueFiles:
        - values-{{ .Values.environmentName }}.yaml
      values: |
        ---
        global:
          {{- toYaml .Values | trim | nindent 10 }}
  destination:
    namespace: {{ .Values.namespace }}
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
