apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: {{ .Release.Name }}-mysql
spec:
  ports:
    - port: 3306
  selector:
    app: {{ .Release.Name }}-mysql
    tier: backend
  clusterIP: None